//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CGTry2.inc.master {
	
	
	public partial class Principal {
		
		protected System.Web.UI.WebControls.ContentPlaceHolder head;
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.Image imgFoto;
		
		protected System.Web.UI.WebControls.Label txtNombreUsuario;
		
		protected System.Web.UI.WebControls.ContentPlaceHolder Encabezado;
		
		protected System.Web.UI.WebControls.ContentPlaceHolder Contenido;
		
		protected System.Web.UI.WebControls.ContentPlaceHolder PiePagina;
		
		protected System.Web.UI.WebControls.HiddenField hdnUsuarioId;
		
		protected System.Web.UI.WebControls.HiddenField hdnUrlPrincipal;
	}
}
